version: "3.8"
services:
  backend:
    build:
      context: ./backend
      args:
        USE_GPU: "false" # Use GPU if available
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USE_CPU_ONLY=false
      - NODE_ENV=production
    volumes:
      - ./backend/weights:/backend/weights # Mount model weights
    restart: always # Restart on failure
