version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DEVICE=cuda # enable cuda
    #   - DEVICE=cpu
      - NODE_ENV=production
      - ALLOWED_ORIGINS=https://smartbin.vercel.app  # 允许前端访问
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
